# title of website
title: zkk's navi

# description of website
description: twofiveoneten's navigation site

# favicon of website
favicon: "https://github.com/twofiveoneten.png?size=40"

# your website url
url: https://twofiveoneten.github.io/navi/

# github profile url
github: "https://github.com/twofiveoneten"

# footer message
footer: © 2023 - 2024 @twofiveoneten

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
# google_analytics: "G-EXE1PJ8CR2"

webstack:
  search:
    enabled: true
    default: google
    # 可选的搜索引擎
    engines:
      - google
      - github
      - weibo
      - baidu
      - bilibili
      - zhihu

content:
  categories:
    - name: 常用推荐
      sites:
        - name: 编辑导航网站
          description: 编辑此导航网站
          url: https://github.dev/twoFiveOneTen/twofiveoneten.github.io
          icon: https://navi.zkk.me/icon/github.dev.png
        - name: zkk的博客
          description: zkk的笔记本
          url: https://zkk.me
          icon: https://navi.zkk.me/icon/zkk.me.png
        - name: webSSH
          description: ssshwifty-WebSSH
          url: https://ssh.byzkk.com
          icon: https://navi.zkk.me/icon/sshwifty.ico
    - name: AI工具
      sites:
        - name: ChatGPT
          description: OpenAI的ChatGPT
          url: https://chat.openai.com
          icon: https://navi.zkk.me/icon/chat.openai.com.png
        - name: Copilot
          description: Microsoft的Copilot
          url: https://copilot.microsoft.com
          icon: https://navi.zkk.me/icon/copilot-microsoft.png
        - name: 智谱清言
          description: 智谱清言，中国的
          url: https://chatglm.cn
          icon: https://navi.zkk.me/icon/chatglm.cn.png
    - name: 调试工具
      sites:
        - name: 上海腾讯云whistle
          description: 上海腾讯云whistle
          url: http://mock.wuwz.net
          icon: https://navi.zkk.me/icon/whistle.png
        - name: 洛杉矶1服whistle
          description: 洛杉矶1服whistle
          url: http://mock.zkk.me
          icon: https://navi.zkk.me/icon/whistle.png
        - name: Traceroute
          description: IPIP.NET的TraceRoute
          url: https://tools.ipip.net/traceroute.php
          icon: https://navi.zkk.me/icon/tools.ipip.net.png
        - name: 洛杉矶hostdare监控
          description: 洛杉矶hostdare探针
          url: http://193.22.152.253/prob.php
          icon: https://navi.zkk.me/icon/hostdare.png
        - name: 网络测速
          description: speedtest.cn宽带测速
          url: https://www.speedtest.cn/
          icon: https://navi.zkk.me/icon/speedtest.cn.png
        - name: 在线发请求apifox
          description: 在线发请求apifox
          url: https://app.apifox.com/
          icon: https://navi.zkk.me/icon/apifox.com.png
    - name: 云存储
      sites:
        - name: dl.zkk.me
          description: 洛杉矶1云盘
          url: https://dl.zkk.me
          icon: https://navi.zkk.me/icon/tinyfilemanager.png
        - name: api.wuwz.net
          description: 上海腾讯云TinyFileManager存储
          url: https://api.wuwz.net
          icon: https://navi.zkk.me/icon/tinyfilemanager.png
        - name: 蓝奏云
          description: 蓝奏云存储
          url: https://zkkfile.lanzn.com
          icon: https://navi.zkk.me/icon/lanzouyun.ico
    - name: 效率
      sites:
        - name: 语雀
          description: 个人知识库
          url: https://www.yuque.com/
          icon: https://navi.zkk.me/icon/yuque.png
        - name: 南航邮箱
          description: 南航邮箱
          url: https://mail.nuaa.edu.cn
          icon: https://navi.zkk.me/icon/nuaa.png
        - name: 云端粘贴板
          description: 国内的一个云端粘贴板
          url: https://netcut.cn/zkk
          icon: https://navi.zkk.me/icon/netcut.cn.png
        - name: 易转换
          description: 在线转换多种文件
          url: https://www.easeconvert.com/
          icon: https://navi.zkk.me/icon/www.easeconvert.com.png
        - name: iconfont
          description: 阿里巴巴图标库
          url: https://iconfont.cn
          icon: https://navi.zkk.me/icon/iconfont.cn.png
        - name: ILoveIMG
          description: 图片格式转换、图片压缩等图片处理
          url: https://www.iloveimg.com/zh-cn
          icon: https://navi.zkk.me/icon/www.iloveimg.com.png
        - name: 草料二维码
          description: 二维码工具
          url: https://cli.im/
          icon: https://navi.zkk.me/icon/cli.im.png
    - name: 资源
      sites:
        - name: ZLibrary
          description: 电子书资源
          url: https://singlelogin.re
          icon: https://navi.zkk.me/icon/singleLogin.re.png
    - name: 树莓派
      sites:
        - name: 树莓派云存储
          description: 树莓派的TinyFileManager
          url: http://frp.zkk.me
          icon: https://navi.zkk.me/icon/tinyfilemanager.png
        - name: 树莓派探针
          description: 树莓派的xprober探针
          url: http://frp.zkk.me/.prober/xprober.php
          icon: https://navi.zkk.me/icon/rasperry.png
        - name: 红色警戒
          description: 搭建在树莓派上的红色警戒网页游戏
          url: http://frp.zkk.me/.ra
          icon: https://navi.zkk.me/icon/ra2.png
        - name: 树莓派连接测速
          description: 公网连接树莓派情况测试
          url: http://frp.zkk.me/.speedtest
          icon: https://navi.zkk.me/icon/rasperry.png
