# title of website
title: navi

# description of website
description: twofiveoneten's navigation site

# favicon of website
favicon: "https://github.com/twofiveoneten.png?size=40"

# your website url
url: https://twofiveoneten.github.io/navi/

# github profile url
github: "https://github.com/twofiveoneten"

# footer message
footer: © 2021-2021 @twofiveoneten

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
google_analytics: "G-EXE1PJ8CR2"

webstack:
  search:
    enabled: true
    default: google
    # 可选的搜索引擎
    engines:
      - google
      - github
      - weibo
      - baidu
      - bilibili
      - zhihu

content:
  categories:
    - name: 常用推荐
      sites:
        - name: zkk的博客
          description: zkk的笔记本
          url: https://zkk.me
    - name: 云存储
      sites:
        - name: dl.zkk.me
          description: 洛杉矶1云盘
          url: https://dl.zkk.me
    - name: 第三方
      sites:
        - name: 云端粘贴板
        description: 国内的一个云端粘贴板
        url: https://netcut.cn/zkk
        
            
