# title of website
title: zkk's navi

# description of website
description: twofiveoneten's navigation site

# favicon of website
favicon: "https://github.com/twofiveoneten.png?size=40"

# your website url
url: https://twofiveoneten.github.io/navi/

# github profile url
github: "https://github.com/twofiveoneten"

# footer message
footer: © 2023 @twofiveoneten

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
google_analytics: "G-EXE1PJ8CR2"

webstack:
  search:
    enabled: true
    default: google
    # 可选的搜索引擎
    engines:
      - google
      - github
      - weibo
      - baidu
      - bilibili
      - zhihu

content:
  categories:
    - name: 常用推荐
      sites:
        - name: 编辑导航网站
          description: 编辑此导航网站
          url: https://github.dev/twoFiveOneTen/twofiveoneten.github.io
        - name: zkk的博客
          description: zkk的笔记本
          url: https://zkk.me
    - name: 调试工具
      sites:
        - name: 上海腾讯云whistle
          description: 上海腾讯云whistle
          url: http://mock.wuwz.net
        - name: 洛杉矶1服whistle
          description: 洛杉矶1服whistle
          url: http://mock.zkk.me
    - name: 云存储
      sites:
        - name: dl.zkk.me
          description: 洛杉矶1云盘
          url: https://dl.zkk.me
        - name: api.wuwz.net
          description: 上海腾讯云TinyFileManager
          url: https://api.wuwz.net
    - name: 办公
      sites:
        - name: 南航邮箱
          description: 南航邮箱
          url: https://mail.nuaa.edu.cn
    - name: 小工具
      sites:
        - name: 云端粘贴板
          description: 国内的一个云端粘贴板
          url: https://netcut.cn/zkk
        - name: 易转换
          description: 在线转换多种文件
          url: https://www.easeconvert.com/
